### ISSUE TITLE
java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by nomadcanuck** [jrhenderson1988/building-microservices-with-spring-boot#1]
Hello @jrhenderson1988,

Your blog [Building Microservices with Spring Boot - Part 1](https://blog.scottlogic.com/2019/10/31/building-microservices-with-spring-boot) was well written, concise and informative. 

I did have a problem with running this sample locally

> 2019-11-09 09:17:11.875 ERROR 10611 --- [et_localhost-17] c.n.e.cluster.ReplicationTaskProcessor   : Network level connection to peer localhost; retrying after delay
> ...
> com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)
> ...
> Caused by: java.net.ConnectException: Connection refused (Connection refused)
> ...
> 

I resolved this by adding `eureka.instance.hostname=localhost` to the discover-service application.properties.

I look forward to reading the next parts of your blog series.

Regards,
Troy

**Comment by jrhenderson1988** [comment]
Hi Troy,

Thanks for the feedback. It is much appreciated!

With regards to your issue, I have taken a quick look this morning and found that I am seeing the same problem. It appears that setting `eureka.client.registerWithEureka` and `eureka.client.fetchRegistry` both to `false` does not do enough to disable peer replication in this instance. Since Eureka is configured to run on a different port, the default value for `eureka.client.serviceUrl.defaultZone` remains as `http://localhost:8761/eureka/` so Eureka attempts to add it as a peer (but it doesn't exist), which leads to this issue.

I've found that specifying the following in `application.properties` for the `discovery-service` also fixes the problem:

    eureka.client.serviceUrl.defaultZone=http://localhost:${server.port}/eureka/

Similar questions and answers on StackOverflow also suggest this approach:

- https://stackoverflow.com/questions/43247458/config-server-and-eureka-server-in-same-application-tries-to-connect-to-localho
- https://stackoverflow.com/questions/31230255/eureka-how-do-i-disable-configure-peer-replication

However, I've noticed that in this case, it still tries to configure a replica but points to itself. This seems to mirror what happens when running on the default port, 8761.

Adding `eureka.instance.hostname=localhost` as you've suggested, appears to make Eureka go a step further and doesn't even attempt to add itself as a peer, which I find is a nicer solution.

Thanks for raising this issue. I'll be pushing up a fix to it very soon and I will also update the blog post accordingly.

Jonathon
